# Generated by Django 3.0.6 on 2020-06-07 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Post Title')),
                ('content', models.TextField(null=True, verbose_name='Post Content')),
                ('post_image', models.ImageField(null=True, upload_to='posts/%d/%m/')),
                ('hash_tag', models.CharField(max_length=255, null=True, verbose_name='Hash Tags')),
                ('created_on', models.BigIntegerField(null=True, verbose_name='Post Created Time')),
                ('updated_on', models.BigIntegerField(null=True, verbose_name='Post Updated Time')),
                ('is_delete', models.BooleanField(default=False, null=True, verbose_name='Deleted')),
                ('like', models.ManyToManyField(null=True, related_name='Likes', to=settings.AUTH_USER_MODEL, verbose_name='Post Likes')),
                ('tag', models.ManyToManyField(null=True, related_name='Tags', to=settings.AUTH_USER_MODEL, verbose_name='Tagged User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Post_Created_By_user', to=settings.AUTH_USER_MODEL, verbose_name='User Id')),
            ],
        ),
    ]
