# Generated by Django 3.0.6 on 2020-06-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0002_auto_20200607_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(null=True, upload_to='posts/%d-%m-%y'),
        ),
    ]
