# Generated by Django 3.0.6 on 2020-06-07 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0003_auto_20200607_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='created_by',
        ),
    ]
