# Generated by Django 3.0.6 on 2020-06-07 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PostApp', '0004_auto_20200607_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Post_Created_By_user', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Post Created Time'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_on',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Post Updated Time'),
        ),
    ]
