# Generated by Django 3.0.6 on 2020-05-30 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=100, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, null=True, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email Address')),
                ('password', models.CharField(max_length=100, null=True, verbose_name='Password')),
                ('date_of_birth', models.BigIntegerField(null=True, verbose_name='Date of Birth')),
                ('created_on', models.BigIntegerField(null=True, verbose_name='Join Date')),
                ('updated_on', models.BigIntegerField(null=True, verbose_name='Update Date')),
                ('is_active', models.BooleanField(default=False, null=True)),
                ('is_staff', models.BooleanField(default=False, null=True)),
                ('is_admin', models.BooleanField(default=False, null=True)),
                ('is_delete', models.BooleanField(default=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='emailHandler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('email_id', models.EmailField(max_length=254, null=True, verbose_name='Email address')),
                ('body', models.TextField(null=True, verbose_name='Body')),
                ('token', models.BigIntegerField(null=True, verbose_name='Token')),
                ('is_sent', models.BooleanField(default=False, null=True, verbose_name='Is sent')),
                ('is_verify', models.BooleanField(default=False, null=True, verbose_name='Is verify')),
                ('retry_count', models.IntegerField(default=0, null=True, verbose_name='Retry counter')),
                ('is_expiry', models.BigIntegerField(null=True, verbose_name='Is expiry')),
                ('sent_on', models.BigIntegerField(null=True, verbose_name='Sent on')),
                ('created_on', models.BigIntegerField(null=True, verbose_name='Created on')),
                ('updated_on', models.BigIntegerField(null=True, verbose_name='Updated on')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user id')),
            ],
        ),
    ]
