# Generated by Django 3.0.6 on 2020-05-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuseraccount',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
