# Generated by Django 3.0.6 on 2020-06-05 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0002_follower'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follower',
            new_name='Follow',
        ),
    ]
