# Generated by Django 3.0.6 on 2020-06-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0003_auto_20200605_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuseraccount',
            name='contact',
            field=models.BigIntegerField(null=True, verbose_name='contact'),
        ),
        migrations.AddField(
            model_name='myuseraccount',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='profile'),
        ),
    ]
