# Generated by Django 3.0.6 on 2020-05-29 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0003_auto_20200526_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuseraccount',
            name='is_verified',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='myuseraccount',
            name='created_on',
            field=models.BigIntegerField(null=True, verbose_name='Join Date'),
        ),
        migrations.AlterField(
            model_name='myuseraccount',
            name='date_of_birth',
            field=models.BigIntegerField(null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='myuseraccount',
            name='is_active',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='myuseraccount',
            name='is_admin',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='myuseraccount',
            name='is_delete',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='myuseraccount',
            name='is_staff',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='myuseraccount',
            name='updated_on',
            field=models.BigIntegerField(null=True, verbose_name='Update Date'),
        ),
        migrations.CreateModel(
            name='emailHandler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('email_id', models.EmailField(max_length=254, null=True, verbose_name='Email address')),
                ('body', models.TextField(null=True, verbose_name='Body')),
                ('token', models.BigIntegerField(null=True, verbose_name='Token')),
                ('is_sent', models.BooleanField(default=False, null=True, verbose_name='Is sent')),
                ('is_expiry', models.BooleanField(default=False, null=True, verbose_name='Is expiry')),
                ('retry_count', models.BigIntegerField(null=True, verbose_name='Retry counter')),
                ('sent_on', models.BigIntegerField(null=True, verbose_name='Sent on')),
                ('created_on', models.BigIntegerField(max_length=40, null=True, verbose_name='Created on')),
                ('updated_on', models.BigIntegerField(max_length=40, null=True, verbose_name='Updated on')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user id')),
            ],
        ),
    ]
