# Generated by Django 3.0.6 on 2020-05-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0004_auto_20200529_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailhandler',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='emailhandler',
            name='created_on',
            field=models.BigIntegerField(null=True, verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='emailhandler',
            name='updated_on',
            field=models.BigIntegerField(null=True, verbose_name='Updated on'),
        ),
    ]
