# Generated by Django 3.0.6 on 2020-05-29 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0005_auto_20200529_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuseraccount',
            name='is_verified',
        ),
    ]
