# Generated by Django 3.0.6 on 2020-05-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0007_auto_20200529_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailhandler',
            name='retry_count',
            field=models.IntegerField(default=0, null=True, verbose_name='Retry counter'),
        ),
    ]
